name: Take screenshots

on:
  push:
  workflow_dispatch:
  schedule:
    # Run daily around 5am Europe/Berlin (3am UTC during CEST, 4am UTC during CET)
    # Cron stays at 3am UTC so winter runs slightly earlier to sidestep DST shifts
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - uses: actions/github-script@v7
      name: Create shots.yml if missing on first run
      with:
        script: |
          const fs = require('fs');
          if (!fs.existsSync('shots.yml')) {
              const desc = context.payload.repository.description;
              let line = '';
              if (desc && (desc.startsWith('http://') || desc.startsWith('https://'))) {
                  line = `- url: ${desc}` + '\n  output: shot.png\n  height: 800';
              } else {
                  line = '# - url: https://www.example.com/\n#   output: shot.png\n#   height: 800';
              }
              fs.writeFileSync('shots.yml', line + '\n');
          }
    - name: Generate rotated URLs and take shots
      run: |
        # Use rotated earth.nullschool.net URLs
        python3 << 'EOF'
        import yaml
        from datetime import datetime, timedelta
        from zoneinfo import ZoneInfo

        urls = [
            {
                "macbook": "https://earth.nullschool.net/#current/wind/isobaric/250hPa/orthographic=9.00,53.00,500",
                "iphone": "https://earth.nullschool.net/#current/wind/isobaric/250hPa/orthographic=9.00,53.00,360",
            },
            {
                "macbook": "https://earth.nullschool.net/#current/wind/isobaric/10hPa/orthographic=-360.00,90.00,500",
                "iphone": "https://earth.nullschool.net/#current/wind/isobaric/10hPa/orthographic=-360.00,90.00,360",
            },
        ]

        shots = []
        localized_dt = datetime.now(ZoneInfo("Europe/Berlin")) + timedelta(hours=3)
        target_date = localized_dt.strftime("%Y-%m-%d")
        print(f"Using Europe/Berlin date (+3h offset): {target_date}")

        coords_rotation = localized_dt.toordinal() % len(urls)

        for idx, (device, (width, height)) in enumerate([('macbook', (2560, 1600)), ('iphone', (1080, 2340))]):
            url = urls[(coords_rotation + idx) % len(urls)][device]

            shots.append({
                'url': url,
                'output': f'wallpaper-{device}-{target_date}.png',
                'width': width,
                'height': height,
                'wait': 6000,  # Longer wait for render-heavy site
                'javascript': '''
                    // Remove UI elements for clean screenshot
                    document.querySelectorAll('body > main > div.earth-bar, body > main > div.cta-bar.kiosk').forEach(el => el.remove());
                '''
            })
        
        # Write to shots_processed.yml
        with open('shots_processed.yml', 'w') as f:
            yaml.dump(shots, f, default_flow_style=False)
        
        # Print the generated URLs for logging
        print("Generated URLs:")
        for shot in shots:
            print(f"- {shot['output']}: {shot['url']}")
        
        EOF
        
        # Take the shots
        shot-scraper multi shots_processed.yml
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
